Repository iFixit/react-commerce, pull requests merged in 2022-12, with the labels that each got.

#1094 Fix wiki text links style
  frontend/templates/product/sections/ProductSection/index.tsx
Labels: QAing

#1151 Product Page: Add Product Specifications Tests
  frontend/tests/jest/tests/ProductSection.test.tsx
Labels: QAE

#1154 Product Page: Add shipping restrictions test
  frontend/tests/jest/tests/ProductSection.test.tsx
Labels: QAE

#1159 Product Page: Add Product Warranty Tests
  frontend/templates/product/sections/ProductSection/index.tsx
  frontend/tests/jest/tests/ProductSection.test.tsx
  frontend/tests/jest/utils.tsx
Labels: QAE

#1148 CompatibleDevice: Add tests
  frontend/tests/jest/tests/CompatibleDevice.test.tsx
  frontend/tests/jest/tests/__snapshots__/CompatibleDevice.test.tsx.snap
Labels: QAE

#1152 Add tests for product compatibility section
  frontend/templates/product/sections/ProductSection/index.tsx
  frontend/tests/jest/tests/ProductSection.test.tsx
Labels: QAE

#1176 Prop 65 warning: Add tests
  frontend/tests/cypress/integration/product-list/parts_page_devices.cy.ts
  frontend/tests/jest/tests/ProductSection.test.tsx
Labels: QAE

#1173 Product Page: Test Review Section
  frontend/tests/jest/__mocks__/products.ts
  frontend/tests/jest/tests/ProductReviews.test.tsx
  frontend/tests/jest/utils.tsx
Labels: QAE

#1189 Playwright: Fix broken pro_user test
  frontend/tests/playwright/utils.ts
Labels: QAE

#1193 Actions: Add workflow to run Playwright tests
  .github/workflows/main.yml
  frontend/playwright.config.ts
  frontend/tests/playwright/product-list/newsletter_subscribe.spec.ts
Labels: QAE

#1177 Product Page: Test Replacement Guides Section
  frontend/tests/jest/tests/ProductReplacementGuide.test.tsx
Labels: QAE

#1180 Playwright Migration: Port Final Batch of Cypress Tests
  .github/workflows/main.yml
  frontend/playwright.config.ts
  frontend/tests/playwright/product-list/collections_scroll.spec.ts
  frontend/tests/playwright/product-list/collections_view_button.spec.ts
  frontend/tests/playwright/product-list/filters.spec.ts
  frontend/tests/playwright/product-list/newsletter_subscribe.spec.ts
  frontend/tests/playwright/product-list/parts_page_devices.spec.ts
  frontend/tests/playwright/product-list/parts_page_search.spec.ts
  frontend/tests/playwright/product-list/parts_results_view.spec.ts
  frontend/tests/playwright/redirect.spec.ts
  frontend/tests/playwright/utils.ts
Labels: external_block
