Repository iFixit/react-commerce, pull requests merged in 2023-11, with the labels that each got.

#2070 Vulcan: Sidebar: Update Image Aspect Ratio
  frontend/templates/troubleshooting/Problem.tsx
  frontend/templates/troubleshooting/index.tsx
Labels: nerdherd

#2081 Add React keys to meta tags
  frontend/layouts/default/index.tsx
  frontend/templates/page/meta-tags.tsx
Labels: enhancement

#2110 Vulcan: Segregate troubleshooting navBar component
  frontend/templates/troubleshooting/components/NavBar.tsx
  frontend/templates/troubleshooting/index.tsx
Labels: 0 maintenance

#2114 Fix Safari 13.1 Bugs
  frontend/components/common/PrerenderedHTML.tsx
  frontend/components/sections/BannersSection/SingleBanner.tsx
  frontend/components/sections/LifetimeWarrantySection.tsx
  packages/ui/cart/drawer/CartDrawerTrigger.tsx
  packages/ui/header/NavigationMenu.tsx
  packages/ui/theme/styles.ts
Labels: 0 bug

#2131 Product images: use fallback images
  frontend/models/components/image.ts
  frontend/models/product/index.ts
  frontend/templates/product/MetaTags.tsx
  frontend/templates/product/sections/ProductOverviewSection/ProductGallery.tsx
  frontend/tests/jest/__mocks__/products/battery.ts
  frontend/tests/jest/__mocks__/products/generic.ts
  frontend/tests/jest/__mocks__/products/part.ts
  frontend/tests/jest/__mocks__/products/tool.ts
Labels: QAing
