Repository iFixit/react-commerce, pull requests merged in 2023-07, with the labels that each got.

#1814 Tests: Unskip mocked tests
  .github/workflows/stress_test.yml
  frontend/tests/playwright/product/disabled-product.spec.ts
  frontend/tests/playwright/product/pro-user.spec.ts
  frontend/tests/playwright/product/product-page-and-cart.spec.ts
  frontend/tests/playwright/product/product-variant.spec.ts
Labels: QAE

#1822 Update README with Verdaccio Authentication Steps
  README.md
Labels: documentation, QAE

#1827 Vulcan: Fix data table layouts
  frontend/templates/troubleshooting/prerendered.tsx
Labels: 0 bug

#1845 Tests: Skip parts-page-navigation test
  frontend/tests/playwright/product-list/parts-page-navigation.spec.ts
Labels: QAE

#1841 Lighthouse: Render a Box instead of a Link when no `href` prop exists
  frontend/templates/troubleshooting/index.tsx
Labels: 0 bug
