Repository iFixit/react-commerce, pull requests merged in 2023-10, with the labels that each got.

#2024 CI Fix: Pin Pnpm Version to 8.8.0
  .github/actions/pnpm-setup/action.yml
Labels: 0 bug, QAE

#2009 Vulcan: Problem Sidebar: Add Related Problems
  frontend/templates/troubleshooting/Problem.tsx
  frontend/templates/troubleshooting/hooks/useTroubleshootingProps.tsx
  frontend/templates/troubleshooting/index.tsx
  frontend/templates/troubleshooting/toc.tsx
Labels: QAing

#2045 Fix prerendered html component ref
  frontend/components/common/PrerenderedHTML.tsx
Labels: 0 bug

#2047 Refactor Shopify Storefront SDK codegen
  README.md
  frontend/.env
  frontend/.env.development
  frontend/.env.production
  frontend/.gitignore
  frontend/app/(defaultLayout)/components/IFixitPageFrame.tsx
  frontend/codegen/config.ts
  frontend/layouts/default/index.tsx
  frontend/lib/shopify-storefront-sdk/generate-schema.js
  frontend/lib/shopify-storefront-sdk/generated/sdk.ts
  frontend/lib/shopify-storefront-sdk/schema.graphql
  frontend/package.json
Labels: 0 maintenance

#2048 Remove Vercel Analytics
  frontend/app/layout.tsx
  frontend/package.json
  frontend/pages/_app.tsx
  pnpm-lock.yaml
Labels: 0 maintenance

#2049 Upgrade Zod to fix vulnerability
  backend/src/plugins/addons/package.json
  backend/src/plugins/addons/yarn.lock
  frontend/package.json
  packages/auth-sdk/package.json
  pnpm-lock.yaml
Labels: 0 bug, security

#2036 Error handling: Rework
  frontend/lib/shopify-storefront-sdk/index.ts
  frontend/lib/strapi-sdk/index.ts
  frontend/sentry.client.config.ts
  frontend/sentry.edge.config.ts
  frontend/templates/product/sections/ProductOverviewSection/AddToCart/NotifyMeForm.tsx
  frontend/templates/troubleshooting/server.tsx
  packages/ifixit-api-client/index.tsx
  packages/ifixit-api-client/package.json
  packages/sentry/index.tsx
  pnpm-lock.yaml
Labels: external_block
