Repository iFixit/react-commerce, pull requests merged in 2023-12, with the labels that each got.

#2149 GitHub Actions: Enable masking option for ECR Login
  .github/workflows/deploy-strapi.yml
Labels: QAE

#2151 Vulcan: Conditionally render Conclusion TOCHeading
  frontend/templates/troubleshooting/components/Causes.tsx
  frontend/templates/troubleshooting/index.tsx
Labels: nerdherd

#2152 Actions: Update `aws-actions/amazon-ecr-login` from v1 to v2
  .github/workflows/deploy-strapi.yml
Labels: QAE

#2161 Product option: Manually handle output text
  frontend/templates/product/sections/ProductOverviewSection/ProductOptions.tsx
Labels: QAing

#2166 Obey Strapi product list redirects
  frontend/lib/strapi-sdk/generated/sdk.ts
  frontend/lib/strapi-sdk/operations/findProductList.graphql
  frontend/models/product-list/server.ts
  frontend/models/product-list/types.ts
  frontend/templates/product-list/server.tsx
Labels: QAing
