Repository iFixit/react-commerce, pull requests merged in 2023-09, with the labels that each got.

#1961 Add placement fields to Strapi FAQ
  backend/src/api/faq/content-types/faq/schema.json
  backend/src/api/product-list/content-types/product-list/schema.json
  backend/src/api/reusable-section/content-types/reusable-section/schema.json
  frontend/lib/strapi-sdk/generated/sdk.ts
  frontend/lib/strapi-sdk/generated/validation.ts
Labels: 0 feature

#1970 Tests: Unskip skipped tests
  frontend/tests/playwright/product/product-page-and-cart.spec.ts
  frontend/tests/playwright/product/product-variant.spec.ts
Labels: QAE

#1981 Tests: Use dev-api-psk in CI workflows
  .github/actions/build-test-frontend/action.yml
  .github/workflows/main.yml
  .github/workflows/stress_test.yml
  frontend/.env.test
  frontend/config/env.ts
  frontend/playwright.config.ts
  frontend/tests/playwright/test-fixtures.ts
  packages/ifixit-api-client/index.tsx
Labels: QAE

#1976 TOC: Polish 2
  frontend/templates/troubleshooting/index.tsx
  frontend/templates/troubleshooting/scrollPercent.tsx
  frontend/templates/troubleshooting/solution.tsx
  frontend/templates/troubleshooting/toc.tsx
  frontend/templates/troubleshooting/tocContext.tsx
Labels: nerdherd

#1987 Tests: skip product-page-and-cart.spec.ts
  frontend/tests/playwright/product/product-page-and-cart.spec.ts
Labels: 0 bug, QAE
