Repository iFixit/react-commerce, pull requests merged in 2023-08, with the labels that each got.

#1889 Tests: Skip flaky tests
  frontend/tests/playwright/product/product-page-and-cart.spec.ts
Labels: QAE

#1894 Tests: Unskip parts-page-navigation.spec.ts
  frontend/tests/playwright/product-list/parts-page-navigation.spec.ts
Labels: QAE

#1901 Robots Header: Stop no-indexing in prod
  frontend/helpers/next-helpers.ts
  frontend/templates/product-list/server.tsx
  frontend/templates/product/server.tsx
  frontend/templates/troubleshooting/server.tsx
Labels: external_block

#1907 Add generated types
  frontend/codegen/config.ts
  frontend/lib/strapi-sdk/generated/sdk.ts
  frontend/lib/strapi-sdk/generated/validation.ts
Labels: 0 maintenance

#1898 View Stats: Add a base component to troubleshooting pages
  frontend/components/common/ViewStats.tsx
  frontend/templates/troubleshooting/hooks/useTroubleshootingProps.tsx
  frontend/templates/troubleshooting/index.tsx
Labels: QAing

#1924 Tests: Drop Firefox from playwright projects
  .github/workflows/main.yml
  frontend/playwright.config.ts
Labels: QAE
