Repository iFixit/react-commerce, pull requests merged in 2023-03, with the labels that each got.

#1452 Include current itemcode in Frequently Bought Together event
  packages/analytics/index.tsx
Labels: matomo

#1447 Define _paq on window if it isn't yet defined: fixes setEcommerceView issue
  packages/analytics/matomo/index.tsx
  packages/analytics/matomo/matomoPush.ts
  packages/analytics/matomo/track-event.ts
  packages/analytics/matomo/usePaq.ts
Labels: matomo

#1458 Tests: Add search for empty query test
  frontend/tests/playwright/product-list/parts_page_search.spec.ts
Labels: QAE

#1459 Github Actions: Add stress-test workflow
  .github/actions/build-test-frontend/action.yml
  .github/actions/playwright-setup/action.yml
  .github/workflows/main.yml
  .github/workflows/stress_test.yml
Labels: QAE

#1520 Stress-test: specify outputs for check-diff job
  .github/workflows/stress_test.yml
Labels: 0 bug, QAE
